name: Testing Package in Laravel Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-in-mcv-server:

    name: Test in MVC Server
    runs-on: ubuntu-latest

    steps:
      - name: Clone Test App Repo in Server
        uses: appleboy/ssh-action@master
        env:
          PATH_CONT: ${{ secrets.SERVER_PATH_MVC }}
          ENV_CONT: ${{ secrets.SERVER_ENV_MVC }}
        with:
          host: ${{ secrets.SERVER_HOST_MVC }}
          username: ${{ secrets.SERVER_USERNAME_MVC }}
          password: ${{ secrets.SERVER_PASSWORD_MVC }}
          port: ${{ secrets.SERVER_PORT_MVC }}
          envs: PATH_CONT,ENV_CONT
          script: |
            echo "done !!"
            ls
