name: Testing Package in Laravel Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-in-mcv-server:

    name: Test in MVC Server
    runs-on: ubuntu-latest

    steps:
      - name: Clone Test App Repo in Server
        uses: appleboy/ssh-action@master
        env:
          PATH_CONT: ${{ secrets.SERVER_PATH_MVC }}
          ENV_CONT: ${{ secrets.SERVER_ENV_MVC }}
        with:
          host: ${{ secrets.SERVER_HOST_MVC }}
          username: ${{ secrets.SERVER_USERNAME_MVC }}
          password: ${{ secrets.SERVER_PASSWORD_MVC }}
          port: ${{ secrets.SERVER_PORT_MVC }}
          envs: PATH_CONT,ENV_CONT,GITHUB_SHA,GITHUB_REF
          script: |
            echo "done !!"
            echo "Commit sha is :"
            echo ${{ github.event.after }}
            echo "Brach sha is :"
            echo ${{ github.head_ref }}
            rm $PATH_CONT/.env
            rm -rf $PATH_CONT
            mkdir $PATH_CONT
            cd $PATH_CONT
            pwd
            git clone git@github.com:salahhusa9/app-test.test.git .
            composer install
            echo ENV_CONT > .env
            mkdir -p storage/{app,public,framework,logs}
            mkdir -p storage/framework/{cache,sessions,testing,views}
            chmod -R 777 storage bootstrap/cache
            vendor/bin/phpunit vendor/laractrl/controlled/
            # composer require laractrl/controlled:dev-main#${{ github.head_ref }}#${{ github.event.after }}
