name: Testing Package in Laravel Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php: [7.4, 8.0]
                laravel: [8.x, 9.x]
                status: [open, close]
                os: [ubuntu-latest, windows-latest]
                include:
                    - laravel: 9.x
                      php: 8.0
                    - laravel: 8.x
                      php: 7.4
                exclude:
                    - laravel: 8.x
                      php: 8.0
                    - laravel: 9.x
                      php: 7.4

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }} (${{ matrix.status }})

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  coverage: none

            - name: Clone Test App and install packege
              run: |
                git clone "https://${{ secrets.ACCESS_TOKEN  }}@github.com/salahhusa9/app-test.test.git" "app"
                cd ./app
                git checkout ${{ matrix.status }}-P${{ matrix.php }}-L${{ matrix.laravel }}
                composer update --prefer-dist --no-interaction --no-suggest
                php -r "copy('.env.example', '.env');"
                chmod -R 777 storage bootstrap/cache
                composer require laractrl/controlled:dev-main#${{ github.head_ref }}#${{ github.event.after }} -W
                php artisan controlled:up ${{ secrets.LARACTRL_KEY }}

            - name: Execute tests
              run: |
                cd ./app
                git checkout ${{ matrix.status }}-P${{ matrix.php }}-L${{ matrix.laravel }}
                php -r "copy('.env.example', '.env');"
                php artisan test

            - name: Execute tests With Publish File
              run: |
                cd ./app
                git checkout ${{ matrix.status }}-P${{ matrix.php }}-L${{ matrix.laravel }}
                php -r "copy('.env.example', '.env');"
                php artisan test
